# edit these values to match that of your production machine
# which will be cloned from
aws_access_key_id: ""
aws_secret_access_key: ""
aws_region: 'us-west-1'
aws_master_username: ""
aws_master_user_password: ""
aws_production_bucket: "" # this bucket is read from
aws_staging_bucket: ""    # this bucket is DELETED and written to!
