# edit these values to match that of your production machine
# which will be cloned from
aws_access_key_id: ''
aws_secret_access_key: ''
aws_region: 'us-west-1'
aws_bucket: ''
db_host: ''
db_port: '5432'
db_password: ''
